export const OTJ_QUEUE = [
  {
    id: "OTJ-001",
    apprentice: "Jamie Okafor",
    avatarColor: "#3b5fe0",
    standard: "Software Developer L4",
    activity: "Attended day release — Software architecture module",
    category: "Day release",
    hours: 6.5,
    date: "20 Mar 2025",
    submitted: "21 Mar 2025",
    evidence: true,
    atRisk: false,
  },
  {
    id: "OTJ-002",
    apprentice: "Priya Sharma",
    avatarColor: "#0d7a52",
    standard: "Data Technician L3",
    activity: "Completed online Python data analysis module",
    category: "Online learning",
    hours: 3.0,
    date: "18 Mar 2025",
    submitted: "19 Mar 2025",
    evidence: false,
    atRisk: true,
  },
  {
    id: "OTJ-003",
    apprentice: "Amara Diallo",
    avatarColor: "#b85c0a",
    standard: "Accounting Technician L4",
    activity: "Workplace project — month-end reconciliation",
    category: "Workplace project",
    hours: 4.0,
    date: "15 Mar 2025",
    submitted: "05 Mar 2025",
    evidence: true,
    atRisk: true,
  },
  {
    id: "OTJ-004",
    apprentice: "Tom Griffiths",
    avatarColor: "#1847d4",
    standard: "HR Support L3",
    activity: "Mentoring session with senior HR manager",
    category: "Mentoring",
    hours: 1.5,
    date: "22 Mar 2025",
    submitted: "23 Mar 2025",
    evidence: false,
    atRisk: false,
  },
  {
    id: "OTJ-005",
    apprentice: "Connor Walsh",
    avatarColor: "#7c3aed",
    standard: "Business Admin L3",
    activity: "Day release — Business communication workshop",
    category: "Day release",
    hours: 7.0,
    date: "20 Mar 2025",
    submitted: "20 Mar 2025",
    evidence: true,
    atRisk: false,
  },
];

export const CATEGORY_COLOR = {
  "Day release": "#1847d4",
  "Online learning": "#0d7a52",
  "Workplace project": "#b85c0a",
  Mentoring: "#7c3aed",
  Other: "#6e6a62",
};
