/**
 * @typedef {'on_track' | 'at_risk' | 'overdue'} RiskStatus
 *
 * @typedef {{ week: string, hours: number, required: number }} WeeklyOtjPoint
 *
 * @typedef {{
 *   id: string,
 *   date: string,
 *   type: 'review' | 'otj_submission' | 'approval' | 'message' | 'status_change',
 *   description: string
 * }} ActivityEvent
 *
 * @typedef {{
 *   id: string,
 *   date: string,
 *   type: 'note' | 'message' | 'review' | 'plan',
 *   title: string,
 *   notes: string,
 *   followUpDate: string,
 *   outcome: string,
 *   createdBy: string
 * }} Intervention
 *
 * @typedef {{
 *   id: string,
 *   date: string,
 *   channel: 'email' | 'sms' | 'portal',
 *   recipient: 'apprentice' | 'provider' | 'manager',
 *   subject: string,
 *   status: 'delivered' | 'pending' | 'failed'
 * }} NotificationRecord
 *
 * @typedef {{
 *   status: RiskStatus,
 *   reason: string,
 *   score: number,
 *   dateFlagged: string,
 *   paceGap: number,
 *   requiredPace: number,
 *   actualPace: number
 * }} RiskMetrics
 *
 * @typedef {{
 *   id: string,
 *   name: string,
 *   initials: string,
 *   avatarColor: string,
 *   employeeId: string,
 *   provider: string,
 *   standard: string,
 *   lineManager: string,
 *   startDate: string,
 *   expectedEndDate: string,
 *   epaDate: string,
 *   otjActual: number,
 *   otjExpected: number,
 *   otjHoursCompleted: number,
 *   otjHoursRequired: number,
 *   lastActivity: string,
 *   lastReviewedAt: string | null,
 *   risk: RiskMetrics,
 *   weeklyOtjTrend: WeeklyOtjPoint[],
 *   activityTimeline: ActivityEvent[],
 *   interventions: Intervention[],
 *   notifications: NotificationRecord[]
 * }} AtRiskApprentice
 *
 * @typedef {{
 *   totalActive: number,
 *   atRisk: number,
 *   overdue: number,
 *   recoveredThisMonth: number
 * }} AtRiskSummary
 */

/** @type {AtRiskApprentice[]} */
export const AT_RISK_APPRENTICES = [
  {
    id: "PS",
    name: "Priya Sharma",
    initials: "PS",
    avatarColor: "#0d7a52",
    employeeId: "ME-2024-002",
    provider: "Aston Training",
    standard: "Data Technician L3",
    lineManager: "Sarah Rahman",
    startDate: "01 Jun 2024",
    expectedEndDate: "31 May 2026",
    epaDate: "20 Oct 2025",
    otjActual: 52,
    otjExpected: 70,
    otjHoursCompleted: 218,
    otjHoursRequired: 420,
    lastActivity: "14 Mar 2025",
    lastReviewedAt: null,
    risk: {
      status: "at_risk",
      reason:
        "OTJ submission frequency declining — 18 percentage points below expected pace over last 6 weeks.",
      score: 62,
      dateFlagged: "01 Mar 2025",
      paceGap: 18,
      requiredPace: 7.5,
      actualPace: 5.4,
    },
    weeklyOtjTrend: [
      { week: "Wk 1", hours: 6.5, required: 7.5 },
      { week: "Wk 2", hours: 4.0, required: 7.5 },
      { week: "Wk 3", hours: 7.0, required: 7.5 },
      { week: "Wk 4", hours: 3.5, required: 7.5 },
      { week: "Wk 5", hours: 5.0, required: 7.5 },
      { week: "Wk 6", hours: 4.5, required: 7.5 },
      { week: "Wk 7", hours: 6.0, required: 7.5 },
      { week: "Wk 8", hours: 3.5, required: 7.5 },
    ],
    activityTimeline: [
      {
        id: "t1",
        date: "14 Mar 2025",
        type: "status_change",
        description: "Risk flag raised — OTJ pace below threshold.",
      },
      {
        id: "t2",
        date: "10 Mar 2025",
        type: "otj_submission",
        description: "OTJ log submitted — 3.5 hours (Week 8).",
      },
      {
        id: "t3",
        date: "01 Mar 2025",
        type: "review",
        description: "Monthly provider update received from Aston Training.",
      },
      {
        id: "t4",
        date: "28 Feb 2025",
        type: "otj_submission",
        description: "OTJ log submitted — 6.0 hours (Week 7).",
      },
      {
        id: "t5",
        date: "15 Feb 2025",
        type: "message",
        description: "Automated reminder sent: OTJ pace below expected.",
      },
      {
        id: "t6",
        date: "01 Feb 2025",
        type: "otj_submission",
        description: "OTJ log submitted — 4.5 hours (Week 6).",
      },
      {
        id: "t7",
        date: "10 Jan 2025",
        type: "approval",
        description: "OTJ entries approved for December 2024.",
      },
    ],
    interventions: [
      {
        id: "i1",
        date: "14 Mar 2025",
        type: "note",
        title: "OTJ Recovery Plan Discussion",
        notes:
          "Spoke with Priya about the OTJ shortfall. Agreed to increase weekly hours target to 9 hrs for next 4 weeks to close the gap.",
        followUpDate: "14 Apr 2025",
        outcome: "pending",
        createdBy: "Sarah Rahman",
      },
    ],
    notifications: [
      {
        id: "n1",
        date: "14 Mar 2025",
        channel: "email",
        recipient: "manager",
        subject: "At-Risk Alert: Priya Sharma — OTJ pace concern",
        status: "delivered",
      },
      {
        id: "n2",
        date: "14 Mar 2025",
        channel: "email",
        recipient: "provider",
        subject: "Action Required: OTJ shortfall for Priya Sharma",
        status: "delivered",
      },
      {
        id: "n3",
        date: "15 Feb 2025",
        channel: "email",
        recipient: "apprentice",
        subject: "Reminder: Your OTJ log is below expected pace",
        status: "delivered",
      },
      {
        id: "n4",
        date: "01 Feb 2025",
        channel: "portal",
        recipient: "manager",
        subject: "Weekly digest: 1 apprentice below OTJ pace",
        status: "delivered",
      },
    ],
  },
  {
    id: "AD",
    name: "Amara Diallo",
    initials: "AD",
    avatarColor: "#b85c0a",
    employeeId: "ME-2024-005",
    provider: "WMG Academy",
    standard: "Accounting Technician L4",
    lineManager: "David Osei",
    startDate: "01 Jan 2024",
    expectedEndDate: "30 Nov 2025",
    epaDate: "30 Nov 2025",
    otjActual: 44,
    otjExpected: 78,
    otjHoursCompleted: 264,
    otjHoursRequired: 600,
    lastActivity: "10 Mar 2025",
    lastReviewedAt: null,
    risk: {
      status: "overdue",
      reason:
        "Critical OTJ shortfall — 34 percentage points below required pace. EPA in 8 months with insufficient hours to recover at current rate.",
      score: 91,
      dateFlagged: "14 Feb 2025",
      paceGap: 34,
      requiredPace: 9.2,
      actualPace: 4.1,
    },
    weeklyOtjTrend: [
      { week: "Wk 1", hours: 3.0, required: 9.2 },
      { week: "Wk 2", hours: 4.5, required: 9.2 },
      { week: "Wk 3", hours: 2.0, required: 9.2 },
      { week: "Wk 4", hours: 5.0, required: 9.2 },
      { week: "Wk 5", hours: 3.5, required: 9.2 },
      { week: "Wk 6", hours: 0.0, required: 9.2 },
      { week: "Wk 7", hours: 4.0, required: 9.2 },
      { week: "Wk 8", hours: 3.0, required: 9.2 },
    ],
    activityTimeline: [
      {
        id: "t1",
        date: "10 Mar 2025",
        type: "status_change",
        description: "Status escalated to Overdue — gap exceeds 30%.",
      },
      {
        id: "t2",
        date: "05 Mar 2025",
        type: "otj_submission",
        description: "OTJ log submitted — 3.0 hours (Week 8).",
      },
      {
        id: "t3",
        date: "28 Feb 2025",
        type: "message",
        description: "Escalation email sent to line manager and provider.",
      },
      {
        id: "t4",
        date: "20 Feb 2025",
        type: "review",
        description: "Emergency review requested with WMG Academy.",
      },
      {
        id: "t5",
        date: "14 Feb 2025",
        type: "status_change",
        description: "Risk flag raised — first At-Risk notification sent.",
      },
      {
        id: "t6",
        date: "28 Jan 2025",
        type: "otj_submission",
        description: "OTJ log submitted — 4.0 hours (Week 7).",
      },
      {
        id: "t7",
        date: "10 Jan 2025",
        type: "message",
        description: "Commitment statement reminder sent — unsigned.",
      },
    ],
    interventions: [
      {
        id: "i1",
        date: "28 Feb 2025",
        type: "plan",
        title: "Intensive OTJ Recovery Plan",
        notes:
          "Agreed 12-hour minimum weekly OTJ target for 8 weeks. WMG Academy to provide additional workplace tasks. Review fortnightly.",
        followUpDate: "14 Mar 2025",
        outcome: "in_progress",
        createdBy: "David Osei",
      },
      {
        id: "i2",
        date: "20 Feb 2025",
        type: "review",
        title: "Emergency Provider Review",
        notes:
          "Three-way call with Amara, David (line manager), and WMG Academy tutor Sunita Patel. Root cause: work schedule changes reducing OTJ time.",
        followUpDate: "28 Feb 2025",
        outcome: "completed",
        createdBy: "David Osei",
      },
    ],
    notifications: [
      {
        id: "n1",
        date: "10 Mar 2025",
        channel: "email",
        recipient: "manager",
        subject: "OVERDUE Alert: Amara Diallo — critical OTJ shortfall",
        status: "delivered",
      },
      {
        id: "n2",
        date: "10 Mar 2025",
        channel: "email",
        recipient: "provider",
        subject: "URGENT: Amara Diallo requires immediate OTJ support",
        status: "delivered",
      },
      {
        id: "n3",
        date: "28 Feb 2025",
        channel: "email",
        recipient: "apprentice",
        subject: "Action Required: Your apprenticeship is at risk",
        status: "delivered",
      },
      {
        id: "n4",
        date: "14 Feb 2025",
        channel: "email",
        recipient: "manager",
        subject: "At-Risk Alert: Amara Diallo — OTJ pace concern",
        status: "delivered",
      },
    ],
  },
  {
    id: "MT",
    name: "Marcus Thompson",
    initials: "MT",
    avatarColor: "#7c3aed",
    employeeId: "ME-2023-014",
    provider: "Birmingham Met College",
    standard: "Operations / Departmental Manager L5",
    lineManager: "Julie Park",
    startDate: "01 Sep 2023",
    expectedEndDate: "31 Aug 2025",
    epaDate: "31 Aug 2025",
    otjActual: 38,
    otjExpected: 82,
    otjHoursCompleted: 266,
    otjHoursRequired: 700,
    lastActivity: "22 Feb 2025",
    lastReviewedAt: null,
    risk: {
      status: "overdue",
      reason:
        "Extended period of low OTJ activity — 44 percentage points below required pace. EPA in 5 months. Recovery now requires 14+ hours per week.",
      score: 96,
      dateFlagged: "10 Jan 2025",
      paceGap: 44,
      requiredPace: 12.5,
      actualPace: 3.8,
    },
    weeklyOtjTrend: [
      { week: "Wk 1", hours: 2.5, required: 12.5 },
      { week: "Wk 2", hours: 5.0, required: 12.5 },
      { week: "Wk 3", hours: 3.0, required: 12.5 },
      { week: "Wk 4", hours: 4.5, required: 12.5 },
      { week: "Wk 5", hours: 1.5, required: 12.5 },
      { week: "Wk 6", hours: 6.0, required: 12.5 },
      { week: "Wk 7", hours: 2.0, required: 12.5 },
      { week: "Wk 8", hours: 4.0, required: 12.5 },
    ],
    activityTimeline: [
      {
        id: "t1",
        date: "22 Feb 2025",
        type: "otj_submission",
        description: "OTJ log submitted — 4.0 hours (Week 8).",
      },
      {
        id: "t2",
        date: "14 Feb 2025",
        type: "review",
        description:
          "Provider progress report received — concern raised about EPA readiness.",
      },
      {
        id: "t3",
        date: "01 Feb 2025",
        type: "message",
        description:
          "Second escalation: line manager notified of overdue status.",
      },
      {
        id: "t4",
        date: "20 Jan 2025",
        type: "otj_submission",
        description: "OTJ log submitted — 2.0 hours (Week 7).",
      },
      {
        id: "t5",
        date: "10 Jan 2025",
        type: "status_change",
        description: "Status escalated to Overdue.",
      },
      {
        id: "t6",
        date: "05 Jan 2025",
        type: "review",
        description: "Mid-programme review overdue — rescheduled for February.",
      },
    ],
    interventions: [
      {
        id: "i1",
        date: "14 Feb 2025",
        type: "plan",
        title: "EPA Readiness Intervention",
        notes:
          "Formal improvement plan initiated. Marcus to log minimum 12 hours OTJ per week. Daily workplace tasks agreed with line manager. Provider to increase contact to weekly check-ins.",
        followUpDate: "28 Feb 2025",
        outcome: "in_progress",
        createdBy: "Julie Park",
      },
    ],
    notifications: [
      {
        id: "n1",
        date: "22 Feb 2025",
        channel: "email",
        recipient: "manager",
        subject: "OVERDUE Alert: Marcus Thompson — EPA at risk",
        status: "delivered",
      },
      {
        id: "n2",
        date: "01 Feb 2025",
        channel: "email",
        recipient: "provider",
        subject: "URGENT: Marcus Thompson OTJ recovery plan required",
        status: "delivered",
      },
      {
        id: "n3",
        date: "10 Jan 2025",
        channel: "email",
        recipient: "manager",
        subject: "At-Risk Alert: Marcus Thompson escalated to Overdue",
        status: "delivered",
      },
      {
        id: "n4",
        date: "10 Jan 2025",
        channel: "email",
        recipient: "apprentice",
        subject:
          "Important: Your apprenticeship progress requires immediate action",
        status: "delivered",
      },
    ],
  },
  {
    id: "SW",
    name: "Sophie Williams",
    initials: "SW",
    avatarColor: "#0ea5e9",
    employeeId: "ME-2024-007",
    provider: "Aston Training",
    standard: "Team Leader / Supervisor L3",
    lineManager: "Sarah Rahman",
    startDate: "01 Apr 2024",
    expectedEndDate: "31 Mar 2026",
    epaDate: "31 Mar 2026",
    otjActual: 55,
    otjExpected: 72,
    otjHoursCompleted: 165,
    otjHoursRequired: 300,
    lastActivity: "20 Mar 2025",
    lastReviewedAt: "25 Mar 2025",
    risk: {
      status: "at_risk",
      reason:
        "OTJ pace has declined over the last 4 weeks following department restructure. 17 percentage points below expected.",
      score: 55,
      dateFlagged: "10 Mar 2025",
      paceGap: 17,
      requiredPace: 6.0,
      actualPace: 4.2,
    },
    weeklyOtjTrend: [
      { week: "Wk 1", hours: 5.5, required: 6.0 },
      { week: "Wk 2", hours: 6.0, required: 6.0 },
      { week: "Wk 3", hours: 4.5, required: 6.0 },
      { week: "Wk 4", hours: 3.0, required: 6.0 },
      { week: "Wk 5", hours: 4.0, required: 6.0 },
      { week: "Wk 6", hours: 3.5, required: 6.0 },
      { week: "Wk 7", hours: 5.0, required: 6.0 },
      { week: "Wk 8", hours: 4.0, required: 6.0 },
    ],
    activityTimeline: [
      {
        id: "t1",
        date: "20 Mar 2025",
        type: "otj_submission",
        description: "OTJ log submitted — 4.0 hours (Week 8).",
      },
      {
        id: "t2",
        date: "10 Mar 2025",
        type: "status_change",
        description:
          "Risk flag raised — OTJ pace declined following department restructure.",
      },
      {
        id: "t3",
        date: "05 Mar 2025",
        type: "review",
        description:
          "6-month review completed. Progress noted as satisfactory but OTJ concern flagged.",
      },
      {
        id: "t4",
        date: "28 Feb 2025",
        type: "otj_submission",
        description: "OTJ log submitted — 5.0 hours (Week 7).",
      },
      {
        id: "t5",
        date: "15 Feb 2025",
        type: "message",
        description: "Provider notified of OTJ pace decline.",
      },
    ],
    interventions: [],
    notifications: [
      {
        id: "n1",
        date: "10 Mar 2025",
        channel: "email",
        recipient: "manager",
        subject: "At-Risk Alert: Sophie Williams — OTJ pace concern",
        status: "delivered",
      },
      {
        id: "n2",
        date: "10 Mar 2025",
        channel: "email",
        recipient: "provider",
        subject: "Action Required: OTJ shortfall for Sophie Williams",
        status: "delivered",
      },
      {
        id: "n3",
        date: "15 Feb 2025",
        channel: "portal",
        recipient: "manager",
        subject: "Weekly digest: 1 apprentice below OTJ pace",
        status: "delivered",
      },
    ],
  },
  {
    id: "KA",
    name: "Kwame Asante",
    initials: "KA",
    avatarColor: "#dc2626",
    employeeId: "ME-2024-011",
    provider: "Birmingham Met College",
    standard: "Customer Service Specialist L3",
    lineManager: "David Osei",
    startDate: "01 Jul 2024",
    expectedEndDate: "30 Jun 2026",
    epaDate: "30 Jun 2026",
    otjActual: 60,
    otjExpected: 77,
    otjHoursCompleted: 168,
    otjHoursRequired: 280,
    lastActivity: "18 Mar 2025",
    lastReviewedAt: null,
    risk: {
      status: "at_risk",
      reason:
        "Missed provider review in February. OTJ pacing 17 percentage points below expected. Provider contact frequency reduced.",
      score: 58,
      dateFlagged: "20 Feb 2025",
      paceGap: 17,
      requiredPace: 5.4,
      actualPace: 3.7,
    },
    weeklyOtjTrend: [
      { week: "Wk 1", hours: 4.5, required: 5.4 },
      { week: "Wk 2", hours: 5.0, required: 5.4 },
      { week: "Wk 3", hours: 3.0, required: 5.4 },
      { week: "Wk 4", hours: 4.0, required: 5.4 },
      { week: "Wk 5", hours: 2.5, required: 5.4 },
      { week: "Wk 6", hours: 4.5, required: 5.4 },
      { week: "Wk 7", hours: 3.5, required: 5.4 },
      { week: "Wk 8", hours: 4.0, required: 5.4 },
    ],
    activityTimeline: [
      {
        id: "t1",
        date: "18 Mar 2025",
        type: "otj_submission",
        description: "OTJ log submitted — 4.0 hours (Week 8).",
      },
      {
        id: "t2",
        date: "20 Feb 2025",
        type: "status_change",
        description:
          "Risk flag raised — missed provider review and declining OTJ pace.",
      },
      {
        id: "t3",
        date: "14 Feb 2025",
        type: "message",
        description: "Provider review missed — rescheduled for March.",
      },
      {
        id: "t4",
        date: "01 Feb 2025",
        type: "otj_submission",
        description: "OTJ log submitted — 3.5 hours (Week 7).",
      },
      {
        id: "t5",
        date: "15 Jan 2025",
        type: "review",
        description:
          "January provider update received. Tutor flagged attendance concern.",
      },
    ],
    interventions: [],
    notifications: [
      {
        id: "n1",
        date: "20 Feb 2025",
        channel: "email",
        recipient: "manager",
        subject: "At-Risk Alert: Kwame Asante — OTJ pace and missed review",
        status: "delivered",
      },
      {
        id: "n2",
        date: "20 Feb 2025",
        channel: "email",
        recipient: "provider",
        subject: "Action Required: Kwame Asante — review overdue",
        status: "delivered",
      },
    ],
  },
  {
    id: "LO",
    name: "Layla Okonkwo",
    initials: "LO",
    avatarColor: "#16a34a",
    employeeId: "ME-2024-003",
    provider: "WMG Academy",
    standard: "HR Support L3",
    lineManager: "Julie Park",
    startDate: "01 Feb 2024",
    expectedEndDate: "31 Jan 2026",
    epaDate: "31 Jan 2026",
    otjActual: 62,
    otjExpected: 78,
    otjHoursCompleted: 223,
    otjHoursRequired: 360,
    lastActivity: "25 Mar 2025",
    lastReviewedAt: null,
    risk: {
      status: "at_risk",
      reason:
        "OTJ hours logged below required pace for 3 consecutive weeks. Gap is 16 percentage points and increasing.",
      score: 52,
      dateFlagged: "05 Mar 2025",
      paceGap: 16,
      requiredPace: 6.9,
      actualPace: 5.1,
    },
    weeklyOtjTrend: [
      { week: "Wk 1", hours: 6.5, required: 6.9 },
      { week: "Wk 2", hours: 7.0, required: 6.9 },
      { week: "Wk 3", hours: 5.5, required: 6.9 },
      { week: "Wk 4", hours: 4.5, required: 6.9 },
      { week: "Wk 5", hours: 4.0, required: 6.9 },
      { week: "Wk 6", hours: 5.0, required: 6.9 },
      { week: "Wk 7", hours: 5.5, required: 6.9 },
      { week: "Wk 8", hours: 4.5, required: 6.9 },
    ],
    activityTimeline: [
      {
        id: "t1",
        date: "25 Mar 2025",
        type: "otj_submission",
        description: "OTJ log submitted — 4.5 hours (Week 8).",
      },
      {
        id: "t2",
        date: "05 Mar 2025",
        type: "status_change",
        description: "Risk flag raised — 3 weeks of below-pace OTJ logging.",
      },
      {
        id: "t3",
        date: "28 Feb 2025",
        type: "review",
        description: "Monthly provider update received from WMG Academy.",
      },
      {
        id: "t4",
        date: "20 Feb 2025",
        type: "otj_submission",
        description: "OTJ log submitted — 5.5 hours (Week 7).",
      },
      {
        id: "t5",
        date: "10 Feb 2025",
        type: "otj_submission",
        description: "OTJ log submitted — 5.0 hours (Week 6).",
      },
      {
        id: "t6",
        date: "01 Feb 2025",
        type: "approval",
        description: "OTJ entries approved for January 2025.",
      },
    ],
    interventions: [],
    notifications: [
      {
        id: "n1",
        date: "05 Mar 2025",
        channel: "email",
        recipient: "manager",
        subject: "At-Risk Alert: Layla Okonkwo — OTJ pace concern",
        status: "delivered",
      },
      {
        id: "n2",
        date: "05 Mar 2025",
        channel: "email",
        recipient: "provider",
        subject: "Action Required: OTJ shortfall for Layla Okonkwo",
        status: "delivered",
      },
    ],
  },
  {
    id: "TG",
    name: "Tom Griffiths",
    initials: "TG",
    avatarColor: "#1847d4",
    employeeId: "ME-2024-009",
    provider: "Aston Training",
    standard: "HR Support L3",
    lineManager: "Sarah Rahman",
    startDate: "01 Sep 2024",
    expectedEndDate: "01 Jun 2026",
    epaDate: "01 Jun 2026",
    otjActual: 31,
    otjExpected: 28,
    otjHoursCompleted: 124,
    otjHoursRequired: 400,
    lastActivity: "25 Mar 2025",
    lastReviewedAt: "28 Mar 2025",
    risk: {
      status: "on_track",
      reason: "Performing above expected OTJ pace. No concerns.",
      score: 8,
      dateFlagged: null,
      paceGap: -3,
      requiredPace: 4.8,
      actualPace: 5.2,
    },
    weeklyOtjTrend: [
      { week: "Wk 1", hours: 5.0, required: 4.8 },
      { week: "Wk 2", hours: 5.5, required: 4.8 },
      { week: "Wk 3", hours: 4.5, required: 4.8 },
      { week: "Wk 4", hours: 5.0, required: 4.8 },
      { week: "Wk 5", hours: 6.0, required: 4.8 },
      { week: "Wk 6", hours: 4.5, required: 4.8 },
      { week: "Wk 7", hours: 5.5, required: 4.8 },
      { week: "Wk 8", hours: 5.0, required: 4.8 },
    ],
    activityTimeline: [
      {
        id: "t1",
        date: "25 Mar 2025",
        type: "otj_submission",
        description: "OTJ log submitted — 5.0 hours (Week 8).",
      },
      {
        id: "t2",
        date: "10 Mar 2025",
        type: "review",
        description: "6-month review completed — progressing well.",
      },
      {
        id: "t3",
        date: "28 Feb 2025",
        type: "approval",
        description: "OTJ entries approved for February 2025.",
      },
    ],
    interventions: [],
    notifications: [],
  },
  {
    id: "JO",
    name: "Jamie Okafor",
    initials: "JO",
    avatarColor: "#3b5fe0",
    employeeId: "ME-2024-001",
    provider: "Birmingham Met College",
    standard: "Software Developer L4",
    lineManager: "David Osei",
    startDate: "01 Mar 2024",
    expectedEndDate: "28 Feb 2026",
    epaDate: "15 Jan 2026",
    otjActual: 68,
    otjExpected: 65,
    otjHoursCompleted: 489,
    otjHoursRequired: 720,
    lastActivity: "28 Mar 2025",
    lastReviewedAt: "01 Mar 2025",
    risk: {
      status: "on_track",
      reason: "Ahead of expected OTJ pace. No concerns.",
      score: 5,
      dateFlagged: null,
      paceGap: -3,
      requiredPace: 6.9,
      actualPace: 7.3,
    },
    weeklyOtjTrend: [
      { week: "Wk 1", hours: 7.5, required: 6.9 },
      { week: "Wk 2", hours: 6.5, required: 6.9 },
      { week: "Wk 3", hours: 8.0, required: 6.9 },
      { week: "Wk 4", hours: 7.0, required: 6.9 },
      { week: "Wk 5", hours: 7.5, required: 6.9 },
      { week: "Wk 6", hours: 6.0, required: 6.9 },
      { week: "Wk 7", hours: 7.5, required: 6.9 },
      { week: "Wk 8", hours: 7.0, required: 6.9 },
    ],
    activityTimeline: [
      {
        id: "t1",
        date: "28 Mar 2025",
        type: "otj_submission",
        description: "OTJ log submitted — 7.0 hours (Week 8).",
      },
      {
        id: "t2",
        date: "15 Mar 2025",
        type: "review",
        description: "12-month review completed. OTJ on pace.",
      },
      {
        id: "t3",
        date: "01 Mar 2025",
        type: "approval",
        description: "OTJ entries approved for February 2025.",
      },
    ],
    interventions: [],
    notifications: [],
  },
];

/** @type {AtRiskSummary} */
export const AT_RISK_SUMMARY = {
  totalActive: AT_RISK_APPRENTICES.length,
  atRisk: AT_RISK_APPRENTICES.filter((a) => a.risk.status === "at_risk").length,
  overdue: AT_RISK_APPRENTICES.filter((a) => a.risk.status === "overdue")
    .length,
  recoveredThisMonth: 2,
};
