export const STATEMENTS = [
  {
    id: "CS-001",
    apprentice: {
      name: "Jamie Okafor",
      initials: "JO",
      avatarColor: "#3b5fe0",
    },
    standard: "Software Developer L4",
    provider: "Birmingham Met College",
    providerContact: { name: "Marcus Reid", email: "mreid@bmet.ac.uk" },
    startDate: "01 Mar 2024",
    endDate: "28 Feb 2026",
    otjHoursAgreed: 720,
    status: "signed",
    employerSigned: {
      signed: true,
      name: "Sarah Rahman",
      date: "05 Mar 2024",
      timestamp: "05 Mar 2024 · 09:41 GMT",
      ip: "82.34.xx.xx",
      method: "Digital declaration",
    },
    providerSigned: {
      signed: true,
      name: "Marcus Reid",
      date: "04 Mar 2024",
      timestamp: "04 Mar 2024 · 16:12 GMT",
    },
    apprenticeSigned: {
      signed: true,
      name: "Jamie Okafor",
      date: "03 Mar 2024",
      timestamp: "03 Mar 2024 · 18:55 GMT",
    },
    needsRenewal: false,
    documentUrl: "#",
  },
  {
    id: "CS-002",
    apprentice: {
      name: "Priya Sharma",
      initials: "PS",
      avatarColor: "#0d7a52",
    },
    standard: "Data Technician L3",
    provider: "Aston Training",
    providerContact: {
      name: "Claire Hobbs",
      email: "c.hobbs@astontraining.co.uk",
    },
    startDate: "01 Jun 2024",
    endDate: "31 May 2026",
    otjHoursAgreed: 420,
    status: "signed",
    employerSigned: {
      signed: true,
      name: "Sarah Rahman",
      date: "08 Jun 2024",
      timestamp: "08 Jun 2024 · 10:03 GMT",
      ip: "82.34.xx.xx",
      method: "Digital declaration",
    },
    providerSigned: {
      signed: true,
      name: "Claire Hobbs",
      date: "07 Jun 2024",
      timestamp: "07 Jun 2024 · 14:27 GMT",
    },
    apprenticeSigned: {
      signed: true,
      name: "Priya Sharma",
      date: "06 Jun 2024",
      timestamp: "06 Jun 2024 · 20:11 GMT",
    },
    needsRenewal: false,
    documentUrl: "#",
  },
  {
    id: "CS-003",
    apprentice: {
      name: "Amara Diallo",
      initials: "AD",
      avatarColor: "#b85c0a",
    },
    standard: "Accounting Technician L4",
    provider: "WMG Academy",
    providerContact: {
      name: "Sunita Patel",
      email: "s.patel@wmgacademy.ac.uk",
    },
    startDate: "01 Jan 2024",
    endDate: "30 Nov 2025",
    otjHoursAgreed: 600,
    status: "pending_employer",
    employerSigned: { signed: false },
    providerSigned: {
      signed: true,
      name: "Sunita Patel",
      date: "28 Dec 2023",
      timestamp: "28 Dec 2023 · 11:18 GMT",
    },
    apprenticeSigned: {
      signed: true,
      name: "Amara Diallo",
      date: "27 Dec 2023",
      timestamp: "27 Dec 2023 · 19:44 GMT",
    },
    needsRenewal: false,
    documentUrl: "#",
  },
  {
    id: "CS-004",
    apprentice: {
      name: "Tom Griffiths",
      initials: "TG",
      avatarColor: "#1847d4",
    },
    standard: "HR Support L3",
    provider: "Aston Training",
    providerContact: {
      name: "Claire Hobbs",
      email: "c.hobbs@astontraining.co.uk",
    },
    startDate: "01 Sep 2024",
    endDate: "01 Jun 2026",
    otjHoursAgreed: null,
    status: "draft",
    employerSigned: { signed: false },
    providerSigned: { signed: false },
    apprenticeSigned: { signed: false },
    needsRenewal: false,
    documentUrl: null,
  },
  {
    id: "CS-005",
    apprentice: {
      name: "Connor Walsh",
      initials: "CW",
      avatarColor: "#7c3aed",
    },
    standard: "Business Admin L3",
    provider: "Birmingham Met College",
    providerContact: { name: "Marcus Reid", email: "mreid@bmet.ac.uk" },
    startDate: "01 Sep 2023",
    endDate: "10 Jul 2025",
    otjHoursAgreed: 420,
    status: "signed",
    employerSigned: {
      signed: true,
      name: "Sarah Rahman",
      date: "10 Sep 2023",
      timestamp: "10 Sep 2023 · 08:55 GMT",
      ip: "82.34.xx.xx",
      method: "Digital declaration",
    },
    providerSigned: {
      signed: true,
      name: "Marcus Reid",
      date: "09 Sep 2023",
      timestamp: "09 Sep 2023 · 15:30 GMT",
    },
    apprenticeSigned: {
      signed: true,
      name: "Connor Walsh",
      date: "08 Sep 2023",
      timestamp: "08 Sep 2023 · 17:22 GMT",
    },
    needsRenewal: true,
    renewalReason: "Programme end date extended — EPA rescheduled to Jul 2025",
    documentUrl: "#",
  },
];
