export const LEVY = {
  balance: 48250,
  committed: 31750,
  expiring: 12400,
  free: 4100,
  monthly: 4200,
  payroll: 840000,
  expiringDays: 67,
  transferred: 8000,
  annualPot: 80400,
  usedThisYear: 31750,
  projectedSpend: 67200,
  projectedSurplus: 13200,
  healthScore: 58,
};

export const MONTHLY_BARS = [
  { month: "Aug", value: 2100 },
  { month: "Sep", value: 2520 },
  { month: "Oct", value: 2016 },
  { month: "Nov", value: 2940 },
  { month: "Dec", value: 2730 },
  { month: "Jan", value: 3360 },
  { month: "Feb", value: 3024 },
  { month: "Mar", value: 3780, current: true },
];

export const APPRENTICES = [
  {
    id: 1,
    name: "Priya Mehta",
    standard: "L4 Engineering",
    cost: 15000,
    levyPct: 100,
    status: "On track",
    sc: "green",
  },
  {
    id: 2,
    name: "James Carter",
    standard: "L3 Business",
    cost: 8000,
    levyPct: 100,
    status: "On track",
    sc: "green",
  },
  {
    id: 3,
    name: "Sophie Adeyemi",
    standard: "L5 Management",
    cost: 18000,
    levyPct: 95,
    status: "At risk",
    sc: "amber",
  },
  {
    id: 4,
    name: "Marcus Webb",
    standard: "L4 Data",
    cost: 14400,
    levyPct: 100,
    status: "On track",
    sc: "green",
  },
  {
    id: 5,
    name: "Kezia Okafor",
    standard: "L3 IT Support",
    cost: 7200,
    levyPct: 80,
    status: "Behind",
    sc: "red",
  },
  {
    id: 6,
    name: "Tom Griffiths",
    standard: "L6 Digital",
    cost: 23400,
    levyPct: 100,
    status: "On track",
    sc: "green",
  },
];

export const TRANSFERS = [
  {
    id: 1,
    org: "Precision Auto Parts",
    amount: 4000,
    sector: "Manufacturing",
    stage: "Active",
  },
  {
    id: 2,
    org: "Warwick Print Co",
    amount: 4000,
    sector: "Print & Design",
    stage: "Pending ESFA",
  },
];

export const EXPIRY_MONTHS = [
  { label: "Apr", year: 2025, amount: 0, urgency: "none" },
  { label: "May", year: 2025, amount: 0, urgency: "none" },
  { label: "Jun", year: 2025, amount: 12400, urgency: "urgent" },
  { label: "Jul", year: 2025, amount: 0, urgency: "none" },
  { label: "Aug", year: 2025, amount: 0, urgency: "none" },
  { label: "Sep", year: 2025, amount: 4200, urgency: "warning" },
  { label: "Oct", year: 2025, amount: 0, urgency: "none" },
  { label: "Nov", year: 2025, amount: 0, urgency: "none" },
  { label: "Dec", year: 2025, amount: 4200, urgency: "scheduled" },
  { label: "Jan", year: 2026, amount: 0, urgency: "none" },
  { label: "Feb", year: 2026, amount: 0, urgency: "none" },
  { label: "Mar", year: 2026, amount: 4200, urgency: "scheduled" },
  { label: "Apr", year: 2026, amount: 0, urgency: "none" },
  { label: "May", year: 2026, amount: 0, urgency: "none" },
  { label: "Jun", year: 2026, amount: 4200, urgency: "future" },
  { label: "Jul", year: 2026, amount: 0, urgency: "none" },
  { label: "Aug", year: 2026, amount: 0, urgency: "none" },
  { label: "Sep", year: 2026, amount: 4200, urgency: "future" },
  { label: "Oct", year: 2026, amount: 0, urgency: "none" },
  { label: "Nov", year: 2026, amount: 0, urgency: "none" },
  { label: "Dec", year: 2026, amount: 4200, urgency: "future" },
  { label: "Jan", year: 2027, amount: 0, urgency: "none" },
  { label: "Feb", year: 2027, amount: 0, urgency: "none" },
  { label: "Mar", year: 2027, amount: 4200, urgency: "future" },
];
