export const LEVY = {
  annual: 80400,
  cap50: 40200,
  used: 8000,
  remaining: 32200,
  expiring: 12400,
  expiryDate: "30 Jun 2025",
  expiryDays: 67,
};

export const ACTIVE_TRANSFERS = [
  {
    id: "DAS-TR-2025-00142",
    recipient: "Precision Auto Parts",
    payeRef: "120/PA12345",
    apprentice: "Chloe Barrett",
    standard: "Engineering Technician L3",
    provider: "Midlands Training Co",
    startDate: "01 Jan 2025",
    expectedEndDate: "31 Dec 2026",
    amount: 4000,
    drawn: 1600,
    monthlyDrawdown: 800,
    contactName: "James Patel",
    contactEmail: "james.patel@precisionauto.co.uk",
    history: [
      { month: "Jan 2025", amount: 800, cumulative: 800 },
      { month: "Feb 2025", amount: 800, cumulative: 1600 },
    ],
  },
  {
    id: "DAS-TR-2025-00098",
    recipient: "Warwick Print Co",
    payeRef: "120/WP67890",
    apprentice: "Ryan Nguyen",
    standard: "Print Technician L3",
    provider: "WMG Academy",
    startDate: "01 Feb 2025",
    expectedEndDate: "31 Jan 2027",
    amount: 4000,
    drawn: 800,
    monthlyDrawdown: 800,
    contactName: "Lisa Chen",
    contactEmail: "l.chen@warwickprint.co.uk",
    history: [{ month: "Feb 2025", amount: 800, cumulative: 800 }],
  },
];

export const HISTORY = [
  {
    id: "DAS-TR-2024-00033",
    recipient: "Steel City Fabrications",
    payeRef: "120/SC99001",
    amount: 3600,
    drawn: 3600,
    standard: "Welding L3",
    startDate: "01 Mar 2024",
    endDate: "28 Feb 2025",
    status: "Complete",
  },
];

export const SME_DIR = [
  {
    id: "sme-001",
    emoji: "⚙️",
    name: "Precision Components Ltd",
    sector: "Manufacturing",
    location: "Coventry",
    employees: 28,
    standard: "Engineering Technician L3",
    apprenticesPlanned: 1,
    fundingNeeded: 4500,
    matchScore: 94,
    matchReason: "Same sector · supply chain partner",
    learnfloVerified: true,
    verificationDetails: "DAS verified · Credit check passed · Mar 2025",
    payeRef: "120/PC11223",
    dasRef: "DAS-SME-2025-0041",
    contact: { name: "Anna Brooks", email: "a.brooks@precisioncomp.co.uk" },
    description:
      "Specialist CNC machining business supplying the automotive sector across the West Midlands.",
    fundingBand: 9000,
    proposedProvider: "Birmingham Met College",
    expectedStart: "Sep 2025",
    dasRegistered: true,
    priorTransfers: 0,
    verificationDate: "Mar 2025",
  },
  {
    id: "sme-002",
    emoji: "🔧",
    name: "Midlands Auto Repairs",
    sector: "Manufacturing",
    location: "Birmingham",
    employees: 15,
    standard: "Vehicle Damage Assessor L3",
    apprenticesPlanned: 2,
    fundingNeeded: 9000,
    matchScore: 81,
    matchReason: "Local supply chain alignment",
    learnfloVerified: true,
    verificationDetails: "DAS verified · Credit check passed · Jan 2025",
    payeRef: "120/MA33445",
    dasRef: "DAS-SME-2025-0052",
    contact: { name: "Tom Willis", email: "t.willis@midlandsauto.co.uk" },
    description:
      "Independent vehicle repair business focusing on fleet customers across the West Midlands.",
    fundingBand: 6000,
    proposedProvider: "Aston Training",
    expectedStart: "Oct 2025",
    dasRegistered: true,
    priorTransfers: 1,
    verificationDate: "Jan 2025",
  },
  {
    id: "sme-003",
    emoji: "🏗️",
    name: "BuildRight Contractors",
    sector: "Construction",
    location: "Wolverhampton",
    employees: 42,
    standard: "Site Supervisor L4",
    apprenticesPlanned: 1,
    fundingNeeded: 7000,
    matchScore: 72,
    matchReason: "Regional proximity · verified",
    learnfloVerified: true,
    verificationDetails: "DAS verified · Credit check passed · Feb 2025",
    payeRef: "120/BR55667",
    dasRef: "DAS-SME-2025-0063",
    contact: { name: "Carol Singh", email: "c.singh@buildrightco.co.uk" },
    description:
      "Specialist in commercial and residential construction across the West Midlands.",
    fundingBand: 9000,
    proposedProvider: "WMG Academy",
    expectedStart: "Nov 2025",
    dasRegistered: true,
    priorTransfers: 0,
    verificationDate: "Feb 2025",
  },
  {
    id: "sme-004",
    emoji: "🍽️",
    name: "Harvest Kitchen",
    sector: "Hospitality",
    location: "Solihull",
    employees: 12,
    standard: "Hospitality Supervisor L3",
    apprenticesPlanned: 1,
    fundingNeeded: 4000,
    matchScore: 45,
    matchReason: "Sector mismatch",
    learnfloVerified: false,
    verificationDetails: null,
    payeRef: null,
    dasRef: "DAS-SME-2025-0077",
    contact: { name: "Mei Zhang", email: "m.zhang@harvestkitchen.co.uk" },
    description:
      "Award-winning restaurant group with multiple sites across the West Midlands.",
    fundingBand: 5000,
    proposedProvider: null,
    expectedStart: "Jan 2026",
    dasRegistered: true,
    priorTransfers: 0,
    verificationDate: null,
  },
];

export const PIPELINE_STAGES = [
  "Initiated",
  "Agreed",
  "DAS Approved",
  "Active",
  "Complete",
];

export const STANDARDS = [
  { label: "Engineering Technician L3", fundingBand: 9000 },
  { label: "Software Developer L4", fundingBand: 18000 },
  { label: "Data Technician L3", fundingBand: 9000 },
  { label: "Site Supervisor L4", fundingBand: 9000 },
  { label: "Business Admin L3", fundingBand: 5000 },
  { label: "Hospitality Supervisor L3", fundingBand: 5000 },
];
