export const APPRENTICES = [
  {
    id: "JO",
    name: "Jamie Okafor",
    initials: "JO",
    avatarColor: "#3b5fe0",
    employeeId: "ME-2024-001",
    cohort: "2024-A",
    cohortLabel: "Mar 2024 cohort",
    standard: "Software Developer L4",
    provider: "Birmingham Met College",
    tutorName: "Marcus Reid",
    tutorEmail: "mreid@bmet.ac.uk",
    lineManager: "David Osei",
    lineManagerEmail: "d.osei@midlandseng.co.uk",
    providerContact: {
      name: "Marcus Reid",
      email: "mreid@bmet.ac.uk",
      phone: "0121 446 4545",
    },
    lastActivity: "28 Mar 2025",
    startDate: "01 Mar 2024",
    expectedEndDate: "28 Feb 2026",
    otjActual: 68,
    otjExpected: 65,
    otjHoursCompleted: 489,
    otjHoursRequired: 720,
    epaDate: "15 Jan 2026",
    epaDaysLeft: 230,
    status: "on_track",
    commitmentSigned: true,
    fundingBand: 18000,
    levyCost: 18000,
    attendance: 94,
    lastProviderUpdate: "28 Mar 2025",
    milestones: [
      { label: "Gateway review", date: "Nov 2025", status: "upcoming" },
      { label: "Mock EPA", date: "Dec 2025", status: "upcoming" },
      { label: "EPA submission", date: "Jan 2026", status: "upcoming" },
    ],
    recentActivity: [
      {
        date: "28 Mar 2025",
        text: "Provider submitted monthly progress update",
      },
      { date: "15 Mar 2025", text: "OTJ log updated — 12 hours added" },
      { date: "01 Mar 2025", text: "12-month review completed" },
    ],
  },
  {
    id: "PS",
    name: "Priya Sharma",
    initials: "PS",
    avatarColor: "#0d7a52",
    employeeId: "ME-2024-002",
    cohort: "2024-B",
    cohortLabel: "Jun 2024 cohort",
    standard: "Data Technician L3",
    provider: "Aston Training",
    tutorName: "Claire Hobbs",
    tutorEmail: "c.hobbs@astontraining.co.uk",
    lineManager: "Sarah Rahman",
    lineManagerEmail: "s.rahman@midlandseng.co.uk",
    providerContact: {
      name: "Claire Hobbs",
      email: "c.hobbs@astontraining.co.uk",
      phone: "0121 359 6299",
    },
    lastActivity: "14 Mar 2025",
    startDate: "01 Jun 2024",
    expectedEndDate: "31 May 2026",
    otjActual: 52,
    otjExpected: 65,
    otjHoursCompleted: 218,
    otjHoursRequired: 420,
    epaDate: "20 Oct 2025",
    epaDaysLeft: 143,
    status: "at_risk",
    commitmentSigned: true,
    fundingBand: 12000,
    levyCost: 12000,
    attendance: 81,
    lastProviderUpdate: "14 Mar 2025",
    milestones: [
      { label: "Progress review", date: "Apr 2025", status: "overdue" },
      { label: "Gateway review", date: "Aug 2025", status: "upcoming" },
      { label: "EPA submission", date: "Oct 2025", status: "upcoming" },
    ],
    recentActivity: [
      { date: "14 Mar 2025", text: "OTJ shortfall flagged by provider" },
      { date: "01 Mar 2025", text: "Attendance dipped below 85% threshold" },
      {
        date: "14 Feb 2025",
        text: "Provider submitted monthly progress update",
      },
    ],
  },
  {
    id: "CW",
    name: "Connor Walsh",
    initials: "CW",
    avatarColor: "#7c3aed",
    employeeId: "ME-2023-008",
    cohort: "2023-C",
    cohortLabel: "Sep 2023 cohort",
    standard: "Business Admin L3",
    provider: "Birmingham Met College",
    tutorName: "Marcus Reid",
    tutorEmail: "mreid@bmet.ac.uk",
    lineManager: "Julie Park",
    lineManagerEmail: "j.park@midlandseng.co.uk",
    providerContact: {
      name: "Marcus Reid",
      email: "mreid@bmet.ac.uk",
      phone: "0121 446 4545",
    },
    lastActivity: "29 Mar 2025",
    startDate: "01 Sep 2023",
    expectedEndDate: "10 Jul 2025",
    otjActual: 88,
    otjExpected: 90,
    otjHoursCompleted: 370,
    otjHoursRequired: 420,
    epaDate: "10 Jul 2025",
    epaDaysLeft: 41,
    status: "epa_ready",
    commitmentSigned: true,
    fundingBand: 8000,
    levyCost: 8000,
    attendance: 97,
    lastProviderUpdate: "29 Mar 2025",
    milestones: [
      { label: "Gateway passed", date: "Feb 2025", status: "complete" },
      { label: "EPA registered", date: "Mar 2025", status: "complete" },
      { label: "EPA assessment", date: "Jul 2025", status: "upcoming" },
    ],
    recentActivity: [
      { date: "29 Mar 2025", text: "Gateway review passed — EPA registered" },
      { date: "10 Mar 2025", text: "Portfolio submitted to EPAO" },
      {
        date: "28 Feb 2025",
        text: "Mock EPA completed — distinction predicted",
      },
    ],
  },
  {
    id: "AD",
    name: "Amara Diallo",
    initials: "AD",
    avatarColor: "#b85c0a",
    employeeId: "ME-2024-005",
    cohort: "2024-A",
    cohortLabel: "Jan 2024 cohort",
    standard: "Accounting Technician L4",
    provider: "WMG Academy",
    tutorName: "Sunita Patel",
    tutorEmail: "s.patel@wmgacademy.ac.uk",
    lineManager: "David Osei",
    lineManagerEmail: "d.osei@midlandseng.co.uk",
    providerContact: {
      name: "Sunita Patel",
      email: "s.patel@wmgacademy.ac.uk",
      phone: "024 7657 4632",
    },
    lastActivity: "10 Mar 2025",
    startDate: "01 Jan 2024",
    expectedEndDate: "30 Nov 2025",
    otjActual: 44,
    otjExpected: 70,
    otjHoursCompleted: 264,
    otjHoursRequired: 600,
    epaDate: "30 Nov 2025",
    epaDaysLeft: 244,
    status: "overdue",
    commitmentSigned: false,
    fundingBand: 15000,
    levyCost: 15000,
    attendance: 78,
    lastProviderUpdate: "10 Mar 2025",
    milestones: [
      { label: "Progress review", date: "Mar 2025", status: "overdue" },
      { label: "OTJ catch-up plan", date: "Apr 2025", status: "upcoming" },
      { label: "Gateway review", date: "Sep 2025", status: "upcoming" },
    ],
    recentActivity: [
      { date: "10 Mar 2025", text: "OTJ shortfall — 26% behind expected pace" },
      {
        date: "28 Feb 2025",
        text: "Commitment statement awaiting employer signature",
      },
      {
        date: "14 Feb 2025",
        text: "Attendance dropped to 78% — below threshold",
      },
    ],
  },
  {
    id: "TG",
    name: "Tom Griffiths",
    initials: "TG",
    avatarColor: "#1847d4",
    employeeId: "ME-2024-009",
    cohort: "2024-D",
    cohortLabel: "Sep 2024 cohort",
    standard: "HR Support L3",
    provider: "Aston Training",
    tutorName: "Claire Hobbs",
    tutorEmail: "c.hobbs@astontraining.co.uk",
    lineManager: "Sarah Rahman",
    lineManagerEmail: "s.rahman@midlandseng.co.uk",
    providerContact: {
      name: "Claire Hobbs",
      email: "c.hobbs@astontraining.co.uk",
      phone: "0121 359 6299",
    },
    lastActivity: "25 Mar 2025",
    startDate: "01 Sep 2024",
    expectedEndDate: "01 Jun 2026",
    otjActual: 31,
    otjExpected: 28,
    otjHoursCompleted: 124,
    otjHoursRequired: 400,
    epaDate: "01 Jun 2026",
    epaDaysLeft: 397,
    status: "on_track",
    commitmentSigned: true,
    fundingBand: 7000,
    levyCost: 7000,
    attendance: 92,
    lastProviderUpdate: "25 Mar 2025",
    milestones: [
      { label: "6-month review", date: "Mar 2025", status: "complete" },
      { label: "Progress review", date: "Jun 2025", status: "upcoming" },
      { label: "Gateway review", date: "Feb 2026", status: "upcoming" },
    ],
    recentActivity: [
      {
        date: "25 Mar 2025",
        text: "6-month review completed — progressing well",
      },
      { date: "10 Mar 2025", text: "OTJ log updated — 8 hours added" },
      {
        date: "28 Feb 2025",
        text: "Provider submitted monthly progress update",
      },
    ],
  },
];
